import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :fanfarr, FanfarrWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# SSL is deliberately NOT forced.
#
# The Phoenix generator enables force_ssl here, excluding only "localhost" and
# "127.0.0.1". That is wrong for this application: Fanfarr is a LAN appliance
# reached by IP, alongside Sonarr and Radarr, neither of which forces HTTPS.
# With it enabled, every request to http://<lan-ip>:7373 answers 301 to
# https://<host>/ and the dashboard is unreachable -- while the container
# healthcheck keeps passing, because it curls localhost, the one excluded host.
#
# The brief requires that a reverse proxy not be needed but not be broken
# either. Forcing SSL breaks the first case outright: without a proxy there is
# nothing listening on 443 to redirect to. Where a proxy is present it
# terminates TLS and issues its own redirect, and Plug.RewriteOn in the
# endpoint honours X-Forwarded-Proto so generated URLs stay correct.

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
