defmodule Fanfarr.Repo.Migrations.ThemeDurationMs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:theme_applications) do
      add :duration_ms, :bigint
    end
  end

  def down do
    alter table(:theme_applications) do
      remove :duration_ms
    end
  end
end
