defmodule Fanfarr.Repo.Migrations.AddScores do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:library_media_items) do
      add :critic_score, :float
      add :critic_score_source, :text
      add :audience_score, :float
      add :audience_score_source, :text
    end
  end

  def down do
    alter table(:library_media_items) do
      remove :audience_score_source
      remove :audience_score
      remove :critic_score_source
      remove :critic_score
    end
  end
end
