defmodule Fanfarr.Repo.Migrations.AddStudioAndCollections do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:library_media_items) do
      add :studio, :text
      add :collections, {:array, :text}, null: false, default: []
    end
  end

  def down do
    alter table(:library_media_items) do
      remove :collections
      remove :studio
    end
  end
end
