defmodule Fanfarr.Repo.Migrations.AddManualTheme do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:library_media_items) do
      add :manual_theme_url, :text
      add :manual_theme_title, :text
    end
  end

  def down do
    alter table(:library_media_items) do
      remove :manual_theme_title
      remove :manual_theme_url
    end
  end
end
