defmodule Fanfarr.Repo.Migrations.RenameEmailToUsername do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:users), :email, to: :username

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    create unique_index(:users, [:username], name: "users_unique_username_index")
  end

  def down do
    drop_if_exists unique_index(:users, [:username], name: "users_unique_username_index")

    create unique_index(:users, [:email], name: "users_unique_email_index")

    rename table(:users), :username, to: :email
  end
end
