defmodule Fanfarr.Repo.Migrations.LibrarySeasons do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:library_media_items) do
      add :season_count, :bigint
    end
  end

  def down do
    alter table(:library_media_items) do
      remove :season_count
    end
  end
end
