defmodule Fanfarr.Repo.Migrations.AddMissingFromPlex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:library_media_items) do
      add :missing_from_plex_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:library_media_items) do
      remove :missing_from_plex_at
    end
  end
end
