defmodule Fanfarr.Repo.Migrations.MediaItemExcluded do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:library_media_items) do
      add :excluded, :boolean
    end
  end

  def down do
    alter table(:library_media_items) do
      remove :excluded
    end
  end
end
