defmodule Fanfarr.Repo.Migrations.CreateResourceModel do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:themerr_entries, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :fetched_at, :utc_datetime_usec, null: false
      add :youtube_theme_edited, :bigint
      add :youtube_theme_added, :bigint
      add :youtube_theme_url, :text
      add :found, :boolean, null: false
      add :external_id, :text, null: false
      add :database, :text, null: false
      add :item_type, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:themerr_entries, [:item_type, :database, :external_id],
             name: "themerr_entries_unique_lookup_index"
           )

    create table(:theme_applications, primary_key: false) do
      add :media_item_id,
          references(:library_media_items,
            column: :id,
            name: "theme_applications_media_item_id_fkey",
            type: :uuid
          ),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :attempted_at, :utc_datetime_usec, null: false
      add :bytes, :bigint
      add :codec, :text
      add :error, :text
      add :dry_run, :boolean, null: false
      add :destination_path, :text
      add :theme_url, :text
      add :status, :text, null: false
      add :method, :text, null: false
      add :source, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:settings, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :value, :text
      add :key, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:settings, [:key], name: "settings_unique_key_index")

    create table(:root_folders, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :checked_at, :utc_datetime_usec
      add :free_bytes, :bigint
      add :writable, :boolean, null: false
      add :accessible, :boolean, null: false
      add :enabled, :boolean, null: false
      add :kind, :text, null: false
      add :label, :text
      add :path, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:root_folders, [:path], name: "root_folders_unique_path_index")

    create table(:library_sections, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :last_synced_at, :utc_datetime_usec
      add :enabled, :boolean, null: false
      add :plex_locations, {:array, :text}, default: []
      add :kind, :text, null: false
      add :title, :text, null: false
      add :plex_key, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:library_sections, [:plex_key],
             name: "library_sections_unique_plex_key_index"
           )

    create table(:library_media_items, primary_key: false) do
      add :section_id,
          references(:library_sections,
            column: :id,
            name: "library_media_items_section_id_fkey",
            type: :uuid
          ),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :last_synced_at, :utc_datetime_usec
      add :added_at, :utc_datetime_usec
      add :local_theme_checked_at, :utc_datetime_usec
      add :local_theme_path, :text
      add :local_theme_present, :boolean, null: false
      add :theme_locked, :boolean
      add :plex_theme_provider, :text
      add :plex_theme_url, :text
      add :plex_thumb_key, :text
      add :tvdb_id, :text
      add :tmdb_id, :text
      add :imdb_id, :text
      add :plex_path, :text
      add :kind, :text, null: false
      add :year, :bigint
      add :title, :text, null: false
      add :guid, :text
      add :plex_rating_key, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:library_media_items, [:plex_rating_key],
             name: "library_media_items_unique_plex_rating_key_index"
           )
  end

  def down do
    drop_if_exists unique_index(:library_media_items, [:plex_rating_key],
                     name: "library_media_items_unique_plex_rating_key_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `library_media_items` table without the `library_media_items_section_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:library_media_items)

    drop_if_exists unique_index(:library_sections, [:plex_key],
                     name: "library_sections_unique_plex_key_index"
                   )

    drop table(:library_sections)

    drop_if_exists unique_index(:root_folders, [:path], name: "root_folders_unique_path_index")

    drop table(:root_folders)

    drop_if_exists unique_index(:settings, [:key], name: "settings_unique_key_index")

    drop table(:settings)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `theme_applications` table without the `theme_applications_media_item_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:theme_applications)

    drop_if_exists unique_index(:themerr_entries, [:item_type, :database, :external_id],
                     name: "themerr_entries_unique_lookup_index"
                   )

    drop table(:themerr_entries)
  end
end
