defmodule Fanfarr.Repo.Migrations.AddLoudness do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:theme_applications) do
      add :loudness_lufs, :float
    end
  end

  def down do
    alter table(:theme_applications) do
      remove :loudness_lufs
    end
  end
end
