#!/usr/bin/env bash
#
# Upgrade mergerfs on the Fanfarr reference host (Ubuntu 24.04, five ext4
# drives pooled into /media/merged-storage/*, Plex on bare metal).
#
# HOST MAINTENANCE, not application code. It lives here so it is versioned and
# reviewable, but it touches nothing belonging to Fanfarr.
#
# Runs in phases, because only one of them is disruptive:
#
#   capture   read-only. Records how the pools are mounted right now.  <-- START HERE
#   install   downloads and installs the new .deb. Does NOT touch running
#             mounts: a live mergerfs keeps using the old binary until remount,
#             so this is safe to run at any time.
#   test      mounts a scratch pool with the new binary and your captured
#             options, to surface deprecated options before they matter.
#   remount   THE DISRUPTIVE ONE. Stops consumers, unmounts, remounts, restarts.
#             Requires --yes.
#   rollback  reinstalls the previous version and remounts. Requires --yes.
#
# Usage:
#   bash scripts/mergerfs-upgrade.sh capture
#   bash scripts/mergerfs-upgrade.sh install
#   bash scripts/mergerfs-upgrade.sh test
#   sudo bash scripts/mergerfs-upgrade.sh remount --yes
#   sudo bash scripts/mergerfs-upgrade.sh rollback --yes
#
set -euo pipefail

TARGET_VERSION="${TARGET_VERSION:-2.42.0}"
DEB="mergerfs_${TARGET_VERSION}.ubuntu-noble_amd64.deb"
DEB_URL="https://github.com/trapexit/mergerfs/releases/download/${TARGET_VERSION}/${DEB}"
STATE_DIR="${STATE_DIR:-$HOME/mergerfs-upgrade}"
POOL_GLOB="${POOL_GLOB:-/media/merged-storage/*}"

RED=$'\033[31m'; GRN=$'\033[32m'; YLW=$'\033[33m'; BLD=$'\033[1m'; RST=$'\033[0m'
say()  { printf '%s\n' "$*"; }
head_() { printf '\n%s== %s ==%s\n' "$BLD" "$*" "$RST"; }
ok()   { printf '%s  ok%s  %s\n' "$GRN" "$RST" "$*"; }
warn() { printf '%s  !!%s  %s\n' "$YLW" "$RST" "$*"; }
die()  { printf '%s  xx  %s%s\n' "$RED" "$*" "$RST" >&2; exit 1; }

need_root() { [ "$(id -u)" -eq 0 ] || die "This phase needs root. Re-run with sudo."; }

# Shell-quote one argument. Deliberately NOT printf %q: that escapes commas
# (rw,nonempty -> rw\,nonempty), and a mangled -o value makes mergerfs fall
# back to defaults instead of the options the pool was actually mounted with.
# Single-quote wrapping is shell-safe and leaves commas alone.
shq() {
  local s=${1//\'/\'\\\'\'}
  printf "'%s'" "$s"
}

confirm_flag() {
  for a in "$@"; do [ "$a" = "--yes" ] && return 0; done
  die "This phase stops Plex and unmounts your media. Re-run with --yes when ready."
}

# ---------------------------------------------------------------- capture ---
phase_capture() {
  head_ "Capturing current state into $STATE_DIR"
  mkdir -p "$STATE_DIR"

  if command -v mergerfs >/dev/null 2>&1; then
    mergerfs --version > "$STATE_DIR/old-version.txt" 2>&1 || true
    say "  current: $(head -1 "$STATE_DIR/old-version.txt")"
  else
    warn "mergerfs not on PATH"
    echo "unknown" > "$STATE_DIR/old-version.txt"
  fi

  dpkg -l mergerfs > "$STATE_DIR/dpkg-state.txt" 2>&1 || true
  local installed
  installed="$(dpkg-query -W -f='${Version}' mergerfs 2>/dev/null || echo '')"
  if [ -n "$installed" ]; then
    printf '%s\n' "$installed" > "$STATE_DIR/old-deb-version.txt"
    ok "installed via dpkg, version $installed (rollback target recorded)"
  else
    warn "not installed via dpkg -- built from source? rollback will need manual work"
  fi

  mount | grep -i mergerfs > "$STATE_DIR/current-mounts.txt" 2>/dev/null || true
  local pool_count
  pool_count="$(wc -l < "$STATE_DIR/current-mounts.txt")"
  say "  active pools: $pool_count"
  sed 's/^/    /' "$STATE_DIR/current-mounts.txt" | cut -c1-140

  # The authoritative record: each running mergerfs process's exact argv,
  # rebuilt into a replayable script. /proc/mounts is NOT sufficient -- it does
  # not show the options the pool was created with.
  head_ "Recording the exact mount commands"
  : > "$STATE_DIR/remount.sh"
  : > "$STATE_DIR/mount-options.txt"
  {
    printf '#!/usr/bin/env bash\n'
    printf '# Generated by mergerfs-upgrade.sh capture on %s\n' "$(date -Is)"
    printf '# Replays the exact argv each pool was mounted with.\n'
    printf 'set -euo pipefail\n\n'
  } >> "$STATE_DIR/remount.sh"

  local found=0
  while read -r pid; do
    [ -r "/proc/$pid/cmdline" ] || continue
    local -a argv=()
    mapfile -d '' -t argv < "/proc/$pid/cmdline"
    [ "${#argv[@]}" -gt 0 ] || continue
    found=$((found + 1))
    local a quoted=""
    for a in "${argv[@]}"; do quoted+="$(shq "$a") "; done
    printf '%s\n' "$quoted" >> "$STATE_DIR/remount.sh"

    # Record the -o value verbatim so the test phase can reuse it unmangled.
    local i
    for ((i = 0; i < ${#argv[@]}; i++)); do
      if [ "${argv[$i]}" = "-o" ] && [ $((i + 1)) -lt ${#argv[@]} ]; then
        printf '%s\n' "${argv[$((i + 1))]}" >> "$STATE_DIR/mount-options.txt"
      fi
    done

    say "    $(printf '%s ' "${argv[@]}" | cut -c1-150)"
  done < <(pgrep -x mergerfs 2>/dev/null || true)

  chmod +x "$STATE_DIR/remount.sh"

  grep -i 'mergerfs\|merged-storage' /etc/fstab > "$STATE_DIR/fstab-mergerfs.txt" 2>/dev/null || true
  local fstab_lines
  fstab_lines="$(wc -l < "$STATE_DIR/fstab-mergerfs.txt")"

  systemctl list-units --type=mount --all --no-legend 2>/dev/null \
    | grep -i 'merged\|media' > "$STATE_DIR/systemd-mounts.txt" || true

  head_ "How the pools will be restored"
  if [ "$fstab_lines" -gt 0 ]; then
    ok "fstab has $fstab_lines entry/entries -- 'mount -a' will restore them"
    sed 's/^/    /' "$STATE_DIR/fstab-mergerfs.txt"
    echo "fstab" > "$STATE_DIR/remount-method"
  elif [ "$found" -gt 0 ]; then
    ok "captured argv for $found pool(s) -- $STATE_DIR/remount.sh will restore them"
    echo "argv" > "$STATE_DIR/remount-method"
  else
    echo "none" > "$STATE_DIR/remount-method"
    die "No fstab entries and no running mergerfs processes found.
     Cannot determine how to remount, so unmounting would strand your pools.
     Find how they are mounted (a script? a systemd unit? mounted by hand?)
     before going further."
  fi

  # The setting Fanfarr's file writer needs to know about.
  head_ "Create policy (which drive a NEW file lands on)"
  if grep -qiE 'category\.create|func\.create' "$STATE_DIR/remount.sh" "$STATE_DIR/fstab-mergerfs.txt" 2>/dev/null; then
    grep -hoiE '(category|func)\.create=[a-z]+' "$STATE_DIR/remount.sh" "$STATE_DIR/fstab-mergerfs.txt" 2>/dev/null \
      | sort -u | sed 's/^/    /'
  else
    say "    not set explicitly -- mergerfs defaults to epmfs (path-preserving),"
    say "    which is what we want: a theme.mp3 lands on the same drive as its show."
  fi

  head_ "Consumers that would be interrupted by a remount"
  detect_consumers | sed 's/^/    /'

  head_ "Capture complete"
  ok "state saved to $STATE_DIR"
  say "  Next: bash $0 install   (safe, does not disturb running mounts)"
}

# Anything with a bind mount under /media, plus a host Plex.
detect_consumers() {
  if systemctl is-active --quiet plexmediaserver 2>/dev/null; then
    say "systemd: plexmediaserver (Plex runs on the host -- playback WILL be interrupted)"
  fi
  if command -v docker >/dev/null 2>&1; then
    local c
    for c in $(docker ps --format '{{.Names}}' 2>/dev/null); do
      if docker inspect "$c" --format '{{range .Mounts}}{{.Source}}{{"\n"}}{{end}}' 2>/dev/null \
         | grep -q '^/media'; then
        say "docker: $c"
      fi
    done
  fi
}

consumer_containers() {
  command -v docker >/dev/null 2>&1 || return 0
  local c
  for c in $(docker ps --format '{{.Names}}' 2>/dev/null); do
    if docker inspect "$c" --format '{{range .Mounts}}{{.Source}}{{"\n"}}{{end}}' 2>/dev/null \
       | grep -q '^/media'; then
      printf '%s\n' "$c"
    fi
  done
}

# ---------------------------------------------------------------- install ---
phase_install() {
  [ -f "$STATE_DIR/remount-method" ] || die "Run the capture phase first."
  need_root
  head_ "Installing mergerfs $TARGET_VERSION"
  say "  Running mounts keep using the current binary until remounted, so this"
  say "  phase changes nothing you can observe. That is expected."

  mkdir -p "$STATE_DIR"
  if [ ! -f "$STATE_DIR/$DEB" ]; then
    say "  downloading $DEB"
    curl -fSL --retry 3 -o "$STATE_DIR/$DEB" "$DEB_URL" || die "download failed: $DEB_URL"
  else
    ok "already downloaded"
  fi

  dpkg -i "$STATE_DIR/$DEB" || die "dpkg install failed"
  ok "installed: $(mergerfs --version 2>&1 | head -1)"

  # Stop a routine apt upgrade from pulling the distro version back over it.
  apt-mark hold mergerfs >/dev/null 2>&1 && ok "held at this version (apt-mark hold)" || true

  say ""
  say "  Pools are still running the OLD binary:"
  mount | grep -i mergerfs | head -1 | sed 's/^/    /' | cut -c1-120
  say ""
  say "  Next: bash $0 test      (safe scratch-mount check)"
  say "  Then: sudo bash $0 remount --yes"
}

# ------------------------------------------------------------------- test ---
phase_test() {
  [ -f "$STATE_DIR/remount.sh" ] || die "Run the capture phase first."
  need_root
  head_ "Test-mounting a scratch pool with the new binary"
  say "  Surfaces options deprecated between your version and $TARGET_VERSION"
  say "  without touching the real pools."

  local opts=""
  if [ -s "$STATE_DIR/mount-options.txt" ]; then
    opts="$(head -1 "$STATE_DIR/mount-options.txt")"
  elif [ -s "$STATE_DIR/fstab-mergerfs.txt" ]; then
    # fstab column 4 holds the options, already in the form mergerfs expects.
    opts="$(awk '!/^[[:space:]]*#/ && NF >= 4 {print $4; exit}' "$STATE_DIR/fstab-mergerfs.txt")"
  fi
  [ -n "$opts" ] || { warn "no captured options to test with; skipping"; return 0; }
  say "  options under test: $opts"

  local mp="/mnt/mergerfs-upgrade-test"
  mkdir -p "$mp"
  # Two real branches, mounted read-only, purely to exercise option parsing.
  local branches="/media/the-biggest-one/MorePlex/TV:/media/red-10-redemption/TV"

  local log="$STATE_DIR/test-mount.log"
  if mergerfs -o "${opts:-defaults},ro" "$branches" "$mp" > "$log" 2>&1; then
    ok "mounted with your options"
    if [ -s "$log" ]; then
      warn "mergerfs emitted output -- check for deprecation warnings:"
      sed 's/^/      /' "$log"
    else
      ok "no warnings"
    fi
    say "  sample contents:"
    ls "$mp" 2>/dev/null | head -3 | sed 's/^/      /'
    umount "$mp" 2>/dev/null || true
    rmdir "$mp" 2>/dev/null || true
    ok "test mount cleaned up"
  else
    umount "$mp" 2>/dev/null || true
    rmdir "$mp" 2>/dev/null || true
    warn "test mount FAILED -- do not run remount until this is understood:"
    sed 's/^/      /' "$log"
    return 1
  fi
}

# ---------------------------------------------------------------- remount ---
phase_remount() {
  [ -f "$STATE_DIR/remount-method" ] || die "Run the capture phase first."
  need_root
  local method; method="$(cat "$STATE_DIR/remount-method")"
  [ "$method" != "none" ] || die "Capture found no way to remount. Refusing."

  head_ "Remounting pools onto $(mergerfs --version 2>&1 | head -1)"
  warn "Plex and the containers below will be stopped, then restarted."

  local containers; containers="$(consumer_containers || true)"
  local plex_was_running=0
  systemctl is-active --quiet plexmediaserver 2>/dev/null && plex_was_running=1

  head_ "Stopping consumers"
  if [ "$plex_was_running" -eq 1 ]; then
    systemctl stop plexmediaserver && ok "stopped plexmediaserver"
  fi
  if [ -n "$containers" ]; then
    # shellcheck disable=SC2086
    docker stop $containers >/dev/null && ok "stopped: $(echo $containers | tr '\n' ' ')"
  fi

  head_ "Unmounting pools"
  local pools=() p
  for p in $POOL_GLOB; do
    mountpoint -q "$p" 2>/dev/null && pools+=("$p")
  done
  [ "${#pools[@]}" -gt 0 ] || warn "no mounted pools matched $POOL_GLOB"

  for p in "${pools[@]}"; do
    if umount "$p" 2>/dev/null; then
      ok "unmounted $p"
    else
      warn "$p busy; showing holders:"
      fuser -vm "$p" 2>&1 | sed 's/^/      /' || true
      die "Could not unmount $p. Nothing else has been changed; pools that were
     already unmounted can be restored with: bash $STATE_DIR/remount.sh"
    fi
  done

  head_ "Remounting"
  if [ "$method" = "fstab" ]; then
    mount -a && ok "mount -a completed"
  else
    bash "$STATE_DIR/remount.sh" && ok "replayed captured mount commands"
  fi

  head_ "Verifying"
  local failed=0
  for p in "${pools[@]}"; do
    if mountpoint -q "$p" && [ -n "$(ls -A "$p" 2>/dev/null)" ]; then
      ok "$p mounted and non-empty"
    else
      warn "$p is NOT correctly mounted"
      failed=1
    fi
  done
  [ "$failed" -eq 0 ] || die "Verification failed. Consumers are still stopped so
     you can investigate safely. Restore with: bash $STATE_DIR/remount.sh"

  head_ "Restarting consumers"
  if [ -n "$containers" ]; then
    # shellcheck disable=SC2086
    docker start $containers >/dev/null && ok "started: $(echo $containers | tr '\n' ' ')"
  fi
  if [ "$plex_was_running" -eq 1 ]; then
    systemctl start plexmediaserver && ok "started plexmediaserver"
  fi

  head_ "Done"
  ok "pools now running $(mergerfs --version 2>&1 | head -1)"
}

# --------------------------------------------------------------- rollback ---
phase_rollback() {
  need_root
  local old; old="$(cat "$STATE_DIR/old-deb-version.txt" 2>/dev/null || true)"
  [ -n "$old" ] || die "No recorded previous version in $STATE_DIR/old-deb-version.txt."

  head_ "Rolling back to mergerfs $old"
  apt-mark unhold mergerfs >/dev/null 2>&1 || true
  apt-get install -y --allow-downgrades "mergerfs=$old" || die "downgrade failed"
  ok "reinstalled $old"
  say "  Now re-run the remount phase to put the pools back on it:"
  say "    sudo bash $0 remount --yes"
}

case "${1:-capture}" in
  capture)  phase_capture ;;
  install)  phase_install ;;
  test)     phase_test ;;
  remount)  shift; confirm_flag "$@"; phase_remount ;;
  rollback) shift; confirm_flag "$@"; phase_rollback ;;
  *) die "Unknown phase '${1}'. One of: capture install test remount rollback" ;;
esac
