defmodule FanfarrWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :fanfarr

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_fanfarr_key",
    signing_salt: "xVJdlbDE",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Honour the forwarding headers a reverse proxy sets, so generated URLs and
  # redirects point at the address the browser actually used rather than at the
  # container. Harmless when no proxy is present -- nothing upstream sets these
  # headers, so there is nothing to rewrite -- but note they are trusted when
  # they do appear, which is the usual arrangement for a LAN service.
  plug Plug.RewriteOn, [:x_forwarded_host, :x_forwarded_port, :x_forwarded_proto]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :fanfarr,
    gzip: not code_reloading?,
    only: FanfarrWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug AshPhoenix.Plug.CheckCodegenStatus
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :fanfarr
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  # The container healthcheck polls /health every 30 seconds, which is two log
  # lines a poll -- around 5,800 a day of nothing, enough to bury a real error
  # and to churn the log rotation. This hook drops those specific requests to
  # :debug while leaving every other request at :info.
  plug Plug.Telemetry,
    event_prefix: [:phoenix, :endpoint],
    log: {FanfarrWeb.RequestLogLevel, :for_conn, []}

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json, AshJsonApi.Plug.Parser],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug FanfarrWeb.Router
end
